services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5342
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest

FROM node:16-alpine

WORKDIR /usr/src/app

# 1. Copia os arquivos de dependência
COPY package*.json ./
COPY prisma ./prisma

# 2. Instala dependências (incluindo Prisma)
RUN npm install

# 3. Copia o restante do código
COPY . .

# 4. Gera o cliente do Prisma
RUN npx prisma generate

CMD ["npm", "run", "start:dev"]
